### ISSUE TITLE
Navigating away while transitioning sets incorrect scroll position

### ISSUE THREAD

**Issue by MartinMuzatko** [kamranahmedse/driver.js#13]
When navigating away from a popup (using the arrow keys) in the middle of an animation to scroll to the visible popup, there is no other scroll event happening to get the correct focus.

![scrollmove](https://user-images.githubusercontent.com/2950505/37330755-6067ad28-26a2-11e8-8b59-7022f96c456d.gif)

**Comment by kamranahmedse** [comment]
Hey @MartinMuzatko could you please test if it is fixed now?

**Comment by MartinMuzatko** [comment]
Is it already deployed to the website? Then it is not working yet :)
I'll install it locally and test it.

**Comment by kamranahmedse** [comment]
It is deployed. yes please and maybe [try to debug this section](https://github.com/kamranahmedse/driver.js/blob/master/src/core/element.js#L99) :)

**Comment by moghya** [comment]
@kamranahmedse @MartinMuzatko  I think this is happening because we are choosing postion to scroll as middle on the basis of  `absoluteElementTop` and `window.pageYOffset`. When we're navigating away our element is already very close to  the bottom of window i.e `window.pageYOffset`. and this way our middle is also very close to `window.pageYOffset` and we're loosing the entire point of scrolling to the middle of element.

I'll try to fix this. Any inputs from your side ?

**Comment by moghya** [comment]
@kamranahmedse @MartinMuzatko surprisingly adding following code fixed it, though this is not a good way to fix it.
```
while (!this.isInView()) {
    this.bringInView();
}
```

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/kamranahmedse/driver.js/commit/62c2a38e6b648b34bebaa3eeee15446c4aaea567. Should be fine now.

**Comment by moghya** [comment]
@kamranahmedse I'm sorry but that still leaves bug present in [here](https://github.com/kamranahmedse/driver.js/blob/25d2d75a7a09368bfdbf8838011cd9394bb54197/src/core/element.js#L88)

**Comment by kamranahmedse** [comment]
@moghya no, there is not.

The issue was related to the scroll, previously we had smooth scroll so it did not immediately scroll to the highlighted element; and if user switches the active element during the scroll, the next scroll was ignored because of the previous scroll being in progress. I just changed it to be `instant` to make it immediately scroll to the element. 

The one that you are referring to, it is already instant and has no issues.
