### ISSUE TITLE
project still maintained?

### ISSUE THREAD

**Issue by nseb** [kamranahmedse/driver.js#305]
Hi,

sorry for my question , but the project still maintained?

**Comment by tector** [comment]
doesn't seem so :(

**Comment by kamranahmedse** [comment]
Hey @nseb and @tector — apologies for the radio silence. Yes, the project is still maintained. 

I have been working on rewriting the project to reduce the bundle size and to refactor some of the design decisions I made. I have been super busy the past few days and couldn't get to work on the project but expect to have something ready by the start of next year.

**Comment by nseb** [comment]
@kamranahmedse thanks for your reply, great news

**Comment by tector** [comment]
@kamranahmedse any update on this?

**Comment by mlisowsk** [comment]
@kamranahmedse did you get stuck on the rewrite? How about just commit+release your rewrite or merge those pull requests and move on to the next release. Looks like a dead-lock right now and would be a shame if this nice project would get stuck. Just a kind suggestion - please don't get offended.
I like Driver.js because the minified version runs on IE8-IE10 (i.e. MS WebBrowser control). Source looks also very nice and easy to read.

**Comment by tector** [comment]
@kamranahmedse any update on this?

**Comment by tector** [comment]
@kamranahmedse now any update on this?

**Comment by kamranahmedse** [comment]
Yes — apologies for the radio silence.
I am planning to launch it by the mid/end of June. You can track the progress at https://github.com/kamranahmedse/driver.js/issues/363.
