### ISSUE TITLE
The progress number doesn't seem to be visible

### ISSUE THREAD

**Issue by oeyoews** [kamranahmedse/driver.js#373]
The progress number doesn't seem to be visible, is this a style issue?

![image](https://github.com/kamranahmedse/driver.js/assets/72405338/6914a102-b22e-4175-b937-0df04618318b)

**Comment by kamranahmedse** [comment]
What browser/operating system are you using? I can't seem to reproduce it.

**Comment by oeyoews** [comment]
I use goole chrome 115 and also use firefox, edge browser to test this problem, both of them have the same situation, my operating system is Linux

**Comment by kamranahmedse** [comment]
I am not able to reproduce this unfortunately. Can you please try debugging? From your screenshot it seems that the HTML is there -- also since it's a single DOM element, I am not sure how `of` is visible while the numbers are not. Could you please try playing with the CSS and see if you are able to get it to work.

I am going to close this for now but if anyone else notices the same issue, please do reopen.

**Comment by kevin10-26** [comment]
So far, the only identified fix seems to manually put progressText inside steps.popover object. Although that would work only if you know how many steps you have. It also happens on Windows (with Firefox and Edge, btw).

In my case, even the numbers issued from {{current}} and {{total}} did not display in the HTML source.

Seems like the bug is caused when user imports driver.js library from the CDN. Haven't tested it with any JS framework yet.
