### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by shmily-jianjian** [kamranahmedse/driver.js#374]
How to add a red border to this mask layer
<img width="221" alt="image" src="https://github.com/kamranahmedse/driver.js/assets/61526716/ac23be13-4d9e-473a-ba60-59b9ee39c7dc">

**Comment by shmily-jianjian** [comment]
How to customize its style

**Comment by LukasWillin** [comment]
@kamranahmedse If I would create a working PR for this. Is there a chance it would be merged?
It would be rather simple: Add a second path, which has (almost) the same `d`-parameters as the first:

```html
<!-- Outer Backdrop Path -->
<path d="
    M1457,0L0,0L0,993L1457,993L1457,0Z
    M248,786.4000244140625 h1161 a5,5 0 0 1 5,5 v48 a5,5 0 0 1 -5,5 h-1161 a5,5 0 0 1 -5,-5 v-48 a5,5 0 0 1 5,-5 z
" style="fill: rgb(0, 0, 0); opacity: 0.7; pointer-events: auto; cursor: auto;"></path>
<!-- Inner Outline Path -->
<path d="
    M248,786.4000244140625 h1161 a5,5 0 0 1 5,5 v48 a5,5 0 0 1 -5,5 h-1161 a5,5 0 0 1 -5,-5 v-48 a5,5 0 0 1 5,-5 z
" style="stroke: red;stroke-width: 0.25rem;fill: none;"></path>
```

I would implement the following options:
- `stageBorderWidth`: `number | string` - Sets the `stroke-width`-style property. If it's of type `number` interpret it as pixels. Otherwise, set it as css style attribute (eg. `".25rem"`
- `stageBorderColor`: `string` - Sets the `stroke`-style property.
- `stageBorderPadding`: `number` - By default the same as `stagePadding`, but can be set to something else.

Alternatively we could call them `stageStrokeWidth` etc. That's up to you to decide.
I could also implement gradient options. But that would be for another issue I think.

Example for a complete svg with a gradient.
```html
<svg class="driver-overlay driver-overlay-animated" viewBox="0 0 1457 993" xmlspace="preserve" xmlnsxlink="http://www.w3.org/1999/xlink" version="1.1" preserveAspectRatio="xMinYMin slice" style="fill-rule: evenodd; clip-rule: evenodd; stroke-linejoin: round; stroke-miterlimit: 2; z-index: 10000; position: fixed; top: 0px; left: 0px; width: 100%; height: 100%;">
  <defs>
    <linearGradient id="gradient" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="#05a"></stop>
      <stop offset="100%" stop-color="#0a5"></stop>
    </linearGradient>
  </defs>
  <path d="
    M1457,0L0,0L0,993L1457,993L1457,0Z
    M248,786.4000244140625 h1161 a5,5 0 0 1 5,5 v48 a5,5 0 0 1 -5,5 h-1161 a5,5 0 0 1 -5,-5 v-48 a5,5 0 0 1 5,-5 z
"
    style="fill: rgb(0, 0, 0); opacity: 0.7; pointer-events: auto; cursor: auto;">
  </path>
  <path d="
    M248,786.4000244140625 h1161 a5,5 0 0 1 5,5 v48 a5,5 0 0 1 -5,5 h-1161 a5,5 0 0 1 -5,-5 v-48 a5,5 0 0 1 5,-5 z
"
    style="stroke: url(#gradient);stroke-width: 0.25rem;fill: none;" >
  </path>
</svg>
```
<img width="1192" height="236" alt="Image" src="https://github.com/user-attachments/assets/6ab29eb4-f182-44a8-9b83-fa552f07a235" />

**Comment by LukasWillin** [comment]
For those who cannot wait, the best solution at the moment looks something like this:
_Note that the overlay will be offset by whatever you set the stroke width to. So you cannot make it too big without it looking ugly. You can play around with transform: scaleX and scaleY to better center the overlay-cutout._
```css
.driver-overlay {
  width: calc(100vw + 0.25rem * 2) !important;
  height: calc(100vh + 0.25rem * 2) !important;
  margin: -0.25rem;
}
.driver-overlay > path {
  stroke: red;
  stroke-width: 0.25rem;
}
```
